spring:
  data:
    mongodb:
      uri: mongodb+srv://amangupta3317:guptag1212@jobListing.1dwlzyn.mongodb.net/jobListing?retryWrites=true&w=majority
      database: jobListing

# Server port configuration
server:
  port: 8080
